# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BigQueryOgdLogRecord.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42igQueryOgdLogRecord.proto\"\xe0\x02\n\tLogRecord\x12\x12\n\nsession_id\x18\x01 \x02(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tuser_data\x18\x03 \x01(\t\x12\x13\n\x0b\x63lient_time\x18\x04 \x01(\x03\x12\x15\n\rclient_offset\x18\x05 \x01(\x05\x12\x13\n\x0bserver_time\x18\x06 \x02(\x03\x12\x12\n\nevent_name\x18\x07 \x02(\t\x12\x12\n\nevent_data\x18\x08 \x02(\t\x12\x14\n\x0c\x65vent_source\x18\t \x02(\t\x12\x12\n\ngame_state\x18\n \x01(\t\x12\x13\n\x0b\x61pp_version\x18\x0b \x02(\x05\x12\x12\n\napp_branch\x18\x0c \x01(\t\x12\x13\n\x0blog_version\x18\r \x02(\x05\x12\x1c\n\x14\x65vent_sequence_index\x18\x0e \x02(\x03\x12\x13\n\x0bremote_addr\x18\x0f \x02(\t\x12\x17\n\x0fhttp_user_agent\x18\x10 \x01(\t')



_LOGRECORD = DESCRIPTOR.message_types_by_name['LogRecord']
LogRecord = _reflection.GeneratedProtocolMessageType('LogRecord', (_message.Message,), {
  'DESCRIPTOR' : _LOGRECORD,
  '__module__' : 'BigQueryOgdLogRecord_pb2'
  # @@protoc_insertion_point(class_scope:LogRecord)
  })
_sym_db.RegisterMessage(LogRecord)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGRECORD._serialized_start=31
  _LOGRECORD._serialized_end=383
# @@protoc_insertion_point(module_scope)
